### ISSUE TITLE
installController  需要添加下编码  

### ISSUE THREAD

**Issue by Dandelion246** [wolf-leo/EasyAdmin8-webman#1]
protected function install(string $username, string $password, array $config): bool|Response
    {
        $installPath = config_path() . DIRECTORY_SEPARATOR . 'install' . DIRECTORY_SEPARATOR;
        $sqlPath     = file_get_contents($installPath . 'sql' . DIRECTORY_SEPARATOR . 'install.sql');
        $sqlArray    = $this->parseSql($sqlPath, $config['prefix'], 'ea_');
        $conn        = mysqli_connect($config['host'], $config['username'], $config['password'], null, $config['port']);
        try {
            mysqli_select_db($conn, $config['database']);
            mysqli_query($conn,'set names ' . $config['charset']);
            foreach ($sqlArray as $sql) {
                mysqli_query($conn, $sql);
            }
            $_password = password($password);

我在wsl2 中运行安装程序 写入数据库时 发现中文乱码了  
添加 mysqli_query($conn,'set names ' . $config['charset']);  后解决了这个问题

**Comment by wolf-leo** [comment]
3Q
